//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsSimulatorWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bidding
    {
        public int id { get; set; }
        public Nullable<int> PlayerId { get; set; }
        public Nullable<int> TeamId { get; set; }
        public Nullable<decimal> TeamBid { get; set; }
        public string BiddingStatus { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Team Team { get; set; }
    }
}
