//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsSimulatorWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventTiming
    {
        public int id { get; set; }
        public System.TimeSpan EventTime { get; set; }
        public string EventType { get; set; }
        public int MatchupId { get; set; }
    
        public virtual Matchup Matchup { get; set; }
    }
}
