//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsSimulatorWebApp.Models
{
    using System;
    
    public enum EventType : int
    {
        Attack = 1,
        Defend = 2,
        Scrum = 3,
        Lineout = 4,
        TryHome = 5,
        TryAway = 6,
        DropGoalHome = 7,
        DropGoalAway = 8,
        LineoutAway = 9,
        ScrumAway = 10,
        Conversion = 11
    }
}
