//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsSimulatorWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeagueEntry
    {
        public int id { get; set; }
        public int LeagueId { get; set; }
        public int TeamId { get; set; }
    
        public virtual League League { get; set; }
        public virtual Team Team { get; set; }
    }
}
